### ISSUE TITLE
Tree visualisation colors

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/open-dataset-inspector#5]
It would be nice if the mapped entities in the tree view would be colored in the color of the dataset the same as in the network view. 

As of now, it is impossible to tell to which dataset the belongs.

**Comment by matejikj** [comment]
Fixed. If it is mapped to the same node, then it is blue-red

**Comment by matejikj** [comment]
![colors](https://user-images.githubusercontent.com/43764322/85219566-482b6280-b3a5-11ea-96e9-c90b11b3d14f.png)
