### ISSUE TITLE
Tree visualisation collapsable

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/open-dataset-inspector#6]
It would be nice if the sub-trees can be collapsed-expanded.

It would also allow for better visualisation of the path, where the whole tree would be preserved only with the relevant sub-trees collapsed.

**Comment by matejikj** [comment]
Tohle fungovalo uz predtim, pokud se kliknulo na nodu, ktera je v tom zobrazeni v posledni urovni, tak se rozvinuly az dalsi 4 urovne, pokud to bylo mozne. Pokud mela jen treba potomky po druhou uroven, tak se rozvinuly jen dalsi 2. A pak pokud nektera noda v posledni urovni z tech rozvinutych mela opet nejake pootmky, sla zase rozvinout. Ale pokud se kliknulo na list, tak se nic nedelo, neslo nic rozvinout. A pokud se klikne na nodu, ktera neni v posledni urovni, tak se vsihcni potomci svinou. 

Tak jsem tento issue bral tak, ze je treba asi lepe zobrazit vybranou path. Kdyz kliknu na nekterou path, tak se mi ten strom zobrazi ne cely, ale pouze to dulezite. Tedy nody, ktere patri path a jeste tedy sourozenci techto nodu. To kvuli tomu, aby uyivatel mohl pripadne rozklikavat sourozenecke nody a pritom, pokud to neni posledni viditelna uroven, aby se ta path neschovala

**Comment by matejikj** [comment]
![pathsView](https://user-images.githubusercontent.com/43764322/85219746-b3296900-b3a6-11ea-878e-b761cbe7848a.png)
