### ISSUE TITLE
Circle visualisation used space

### ISSUE THREAD

**Issue by skodapetr** [mff-uk/open-dataset-inspector#7]
When only two nodes are shown,  the inner node consumes all space of the parent.
It would be better to make the inner one smaller so the user can immediately see that there are two nodes on the screen not only one.
![circle-visualisation](https://user-images.githubusercontent.com/3341693/85200573-ef9e8b80-b2f8-11ea-8241-0a89435a2625.png)

**Comment by matejikj** [comment]
![usedSpace](https://user-images.githubusercontent.com/43764322/85219506-a6a41100-b3a4-11ea-8c6f-bf790e8e399d.png)
fixed
